name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: [runnerset=default-runners]
    env: 
      GO111MODULE: off
    steps:
      - name: Checkout search content repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GOLANGLINT_CI }}
      - run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.43
          args: --timeout=3m --verbose